--------------------------------------------------------
--  Arquivo criado - Segunda-feira-Agosto-23-2021   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table PEDIDO_DADOS_GERAIS
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."PEDIDO_DADOS_GERAIS" 
   (	"NUMERO_PEDIDO" NUMBER(10,0), 
	"DATA_EMISSAO" DATE, 
	"CODIGO_CLIENTE" NUMBER(10,0), 
	"VALOR_TOTAL" NUMBER(10,2)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

   COMMENT ON COLUMN "SYSTEM"."PEDIDO_DADOS_GERAIS"."NUMERO_PEDIDO" IS 'CHAVE DO NÚMERO DO PEDIDO';
   COMMENT ON COLUMN "SYSTEM"."PEDIDO_DADOS_GERAIS"."DATA_EMISSAO" IS 'DATA DO PEDIDO';
   COMMENT ON COLUMN "SYSTEM"."PEDIDO_DADOS_GERAIS"."CODIGO_CLIENTE" IS 'CHAVE DA TABELA DE CLIENTE';
   COMMENT ON COLUMN "SYSTEM"."PEDIDO_DADOS_GERAIS"."VALOR_TOTAL" IS 'VALOR TOTAL DO PEDIDO';
--------------------------------------------------------
--  DDL for Table PEDIDO_PRODUTOS
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."PEDIDO_PRODUTOS" 
   (	"CODIGO" NUMBER(10,0), 
	"NUMERO_PEDIDO" NUMBER(10,0), 
	"CODIGO_PRODUTO" NUMBER(10,0), 
	"QUANTIDADE" NUMBER(10,0), 
	"VALOR_UNITARIO" NUMBER(10,2), 
	"VALOR_TOTAL" NUMBER(10,2)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

   COMMENT ON COLUMN "SYSTEM"."PEDIDO_PRODUTOS"."CODIGO" IS 'CHAVE SEQUENCE DA TABELA';
   COMMENT ON COLUMN "SYSTEM"."PEDIDO_PRODUTOS"."NUMERO_PEDIDO" IS 'FK DO PEDIDO_DOS_GERAIS';
   COMMENT ON COLUMN "SYSTEM"."PEDIDO_PRODUTOS"."CODIGO_PRODUTO" IS 'FK DO PRODUTO';
   COMMENT ON COLUMN "SYSTEM"."PEDIDO_PRODUTOS"."QUANTIDADE" IS 'QUANTIDADE DO PRODUTO';
   COMMENT ON COLUMN "SYSTEM"."PEDIDO_PRODUTOS"."VALOR_UNITARIO" IS 'VALOR UNITARIO DO PRODUTO';
   COMMENT ON COLUMN "SYSTEM"."PEDIDO_PRODUTOS"."VALOR_TOTAL" IS 'VALOR_TOTAL_PEDIDO';
--------------------------------------------------------
--  DDL for Table PRODUTOS
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."PRODUTOS" 
   (	"CODIGO" NUMBER(10,0), 
	"DESCRICAO" VARCHAR2(300 BYTE), 
	"PRECO_VENDA" NUMBER(10,2)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

   COMMENT ON COLUMN "SYSTEM"."PRODUTOS"."CODIGO" IS 'Código do Produto';
   COMMENT ON COLUMN "SYSTEM"."PRODUTOS"."DESCRICAO" IS 'Descrição do Produto';
   COMMENT ON COLUMN "SYSTEM"."PRODUTOS"."PRECO_VENDA" IS 'Preço da Venda';
--------------------------------------------------------
--  DDL for Table CLIENTES
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."CLIENTES" 
   (	"CODIGO" NUMBER, 
	"NOME" VARCHAR2(200 BYTE), 
	"CIDADE" VARCHAR2(200 BYTE), 
	"UF" VARCHAR2(2 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

   COMMENT ON COLUMN "SYSTEM"."CLIENTES"."CODIGO" IS 'Código do Cliente';
   COMMENT ON COLUMN "SYSTEM"."CLIENTES"."NOME" IS 'Nome do Cliente';
   COMMENT ON COLUMN "SYSTEM"."CLIENTES"."UF" IS 'Descrição UF';
--------------------------------------------------------
--  DDL for Index TB_PEDIDO_DADOS_GERAIS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."TB_PEDIDO_DADOS_GERAIS_PK" ON "SYSTEM"."PEDIDO_DADOS_GERAIS" ("NUMERO_PEDIDO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PRODUTOS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."PRODUTOS_PK" ON "SYSTEM"."PRODUTOS" ("CODIGO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index CLIENTES_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."CLIENTES_PK" ON "SYSTEM"."CLIENTES" ("CODIGO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Trigger SEQ_CODIGO_PEDIDO_PRODUTOS
--------------------------------------------------------

  CREATE OR REPLACE NONEDITIONABLE TRIGGER "SYSTEM"."SEQ_CODIGO_PEDIDO_PRODUTOS" 
   before insert on "SYSTEM"."PEDIDO_PRODUTOS" 
   for each row 
begin  
   if inserting then 
      if :NEW."CODIGO" is null then 
         select ROLLING_EVENT_SEQ$.nextval into :NEW."CODIGO" from dual; 
      end if; 
   end if; 
end;

/
ALTER TRIGGER "SYSTEM"."SEQ_CODIGO_PEDIDO_PRODUTOS" ENABLE;
--------------------------------------------------------
--  DDL for Trigger SEQ_PRODUTOS_CODIGO
--------------------------------------------------------

  CREATE OR REPLACE NONEDITIONABLE TRIGGER "SYSTEM"."SEQ_PRODUTOS_CODIGO" 
   before insert on "SYSTEM"."PRODUTOS" 
   for each row 
begin  
   if inserting then 
      if :NEW."CODIGO" is null then 
         select ROLLING_EVENT_SEQ$.nextval into :NEW."CODIGO" from dual; 
      end if; 
   end if; 
end;

/
ALTER TRIGGER "SYSTEM"."SEQ_PRODUTOS_CODIGO" ENABLE;
--------------------------------------------------------
--  Constraints for Table PEDIDO_DADOS_GERAIS
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."PEDIDO_DADOS_GERAIS" MODIFY ("NUMERO_PEDIDO" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."PEDIDO_DADOS_GERAIS" MODIFY ("CODIGO_CLIENTE" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."PEDIDO_DADOS_GERAIS" MODIFY ("VALOR_TOTAL" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."PEDIDO_DADOS_GERAIS" ADD CONSTRAINT "TB_PEDIDO_DADOS_GERAIS_PK" PRIMARY KEY ("NUMERO_PEDIDO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table PEDIDO_PRODUTOS
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."PEDIDO_PRODUTOS" MODIFY ("CODIGO" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."PEDIDO_PRODUTOS" MODIFY ("NUMERO_PEDIDO" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."PEDIDO_PRODUTOS" MODIFY ("CODIGO_PRODUTO" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table PRODUTOS
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."PRODUTOS" MODIFY ("CODIGO" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."PRODUTOS" MODIFY ("DESCRICAO" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."PRODUTOS" MODIFY ("PRECO_VENDA" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."PRODUTOS" ADD CONSTRAINT "PRODUTOS_PK" PRIMARY KEY ("CODIGO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table CLIENTES
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."CLIENTES" MODIFY ("CODIGO" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."CLIENTES" ADD CONSTRAINT "TABLE1_PK" PRIMARY KEY ("CODIGO")
  USING INDEX (CREATE UNIQUE INDEX "SYSTEM"."CLIENTES_PK" ON "SYSTEM"."CLIENTES" ("CODIGO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" )  ENABLE;
  ALTER TABLE "SYSTEM"."CLIENTES" MODIFY ("NOME" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table PEDIDO_DADOS_GERAIS
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."PEDIDO_DADOS_GERAIS" ADD CONSTRAINT "PEDIDO_CLIENTES" FOREIGN KEY ("CODIGO_CLIENTE")
	  REFERENCES "SYSTEM"."CLIENTES" ("CODIGO") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table PEDIDO_PRODUTOS
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."PEDIDO_PRODUTOS" ADD CONSTRAINT "PEDIDOS_PRODUTOS_FK" FOREIGN KEY ("NUMERO_PEDIDO")
	  REFERENCES "SYSTEM"."PEDIDO_DADOS_GERAIS" ("NUMERO_PEDIDO") ENABLE;
  ALTER TABLE "SYSTEM"."PEDIDO_PRODUTOS" ADD CONSTRAINT "PRODUTO_PEDIDO_PRODUTO" FOREIGN KEY ("CODIGO_PRODUTO")
	  REFERENCES "SYSTEM"."PRODUTOS" ("CODIGO") ENABLE;
